FROM debian

RUN sudo apt update -y \
  && sudo apt upgrade -y \
  && sudo apt install -y \
    git dnsutils \
  && sudo apt clean \
  && sudo apt autoremove -y --purge \
  && sudo rm -rf /var/lib/apt/lists/*
